### ISSUE TITLE
'Slice' property error when loading gCNV sample

### ISSUE THREAD

**Issue by stephditroia** [broadinstitute/tgg-viewer#11]
I ran across this error when loading gCNV sample `denoised_copy_ratios-RP-1833_FLE_FAM114_GBMID00251_1_D1_v1_Exome_GCP`

![image](https://user-images.githubusercontent.com/44381119/104376007-4ddbc780-54f2-11eb-8ddb-ce9e3069f64d.png)

**Comment by bw2** [comment]
Sorry for missing this earlier. Is this still an issue you're running into?

**Comment by stephditroia** [comment]
This sample works with the new gCNV json

**Comment by bw2** [comment]
Great!
