### ISSUE TITLE
files not visualized

### ISSUE THREAD

**Issue by capricy** [broadinstitute/tgg-viewer#32]
I have files at google cloud and provided the path to the tgg-viewer. I could see them at side bar under Samples. However, when I selected them, I got the message of "not found".

Could you please help to figure why?

Thanks.

C.

**Comment by bw2** [comment]
Apologies for missing this earlier. One possible issue is permissions. Are you sure that the username you are using to login to tgg-viewer also has read access to the google storage path(s) you're trying to visualize?
One way to check is to run `gsutil ls` on the command line.
